OnlineTicaretSitesi/Models/Siniflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace OnlineTicaretSitesi.Models.Siniflar
{
    public class Departman
    {
        [Key]
        public int DepartmanID { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string DepartmanAd { get; set; }
        public bool Durum { get; set; }
        public ICollection<Personel> Personels { get; set; }

    }
}

OnlineTicaretSitesi/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineTicaretSitesi.Models.Siniflar;

namespace OnlineTicaretSitesi.Controllers
{
    public class DepartmanController : Controller
    {
        // GET: Departman
        Context db = new Context();
        public ActionResult Index()
        {
            var degerler = db.Departmans.Where(x => x.Durum).ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult DepartmanEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DepartmanEkle(Departman d)
        {
            d.Durum = true;
            db.Departmans.Add(d);
            
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanSil(int id)
        {
            var dpt = db.Departmans.Find(id);
            dpt.Durum = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanGetir(int id)
        {
            var dpt = db.Departmans.Find(id);
            
            return View("DepartmanGetir", dpt);
        }

        public ActionResult DepartmanGuncelle(Departman dpr)
        {
            var dpt = db.Departmans.Find(dpr.DepartmanID);

            dpt.DepartmanAd = dpr.DepartmanAd;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanDetay(int id)
        {
            var degerler = db.Personels.Where(x => x.Departmanid == id).ToList();
            var dpt = db.Departmans.Where(x => x.DepartmanID == id).Select(y => y.DepartmanAd).FirstOrDefault();
            ViewBag.d = dpt;
            return View(degerler);
        }
        public ActionResult DepartmanPersonelSatis(int id)
        {
            var degerler = db.SatisHarekets.Where(x => x.Personelid == id).ToList();
            var per = db.Personels.Where(x => x.PersonelID == id).Select(y => y.PersonelAd +" "+ y.PersonelSoyad).FirstOrDefault();
            ViewBag.dpers = per;
            return View(degerler);
        }
    }
}

OnlineTicaretSitesi/Views/Departman/DepartmanDetay.cshtml
@using OnlineTicaretSitesi.Models.Siniflar
@model List<Personel>
@{
	ViewBag.Title = "DepartmanDetay";
	Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Departman Detay</h2>
<br />


<ol class="breadcrumb mb-4">
	<li class="breadcrumb-item active">Departman Adı: @ViewBag.d</li> 
</ol>


<table class="table table-hover">

	<tr>
		<th>Personel ID</th>
		<th>Personel</th>
		
		<th>Satışlar</th>
	</tr>

	@foreach (var x in Model)
	{
		<tr>
			<td>@x.PersonelID</td>
            <td>@x.PersonelAd @x.PersonelSoyad </td>
		
			
			<td><a href="/Departman/DepartmanPersonelSatis/@x.PersonelID" class="btn btn-default" style="background-color:orange">Satışlar</a></td>
		</tr>
	}
</table>

OnlineTicaretSitesi/Views/Departman/DepartmanEkle.cshtml
@model OnlineTicaretSitesi.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<form autocomplete="off" class="form-group" method="post">
    <div style="margin-top:20px">
        <label>Departman Adı : </label>
        @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
    </div>
    <div style="margin-top:30px;margin-left:97px">
        <button class="btn btn-warning">Kategori Ekle</button>
    </div>
</form>

OnlineTicaretSitesi/Views/Departman/DepartmanGetir.cshtml
@model OnlineTicaretSitesi.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Güncelleme</h2>
<br />
@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.DepartmanAd)
        @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-controll" })
        @Html.HiddenFor(x => x.DepartmanID)

    </div>
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

OnlineTicaretSitesi/Views/Departman/DepartmanPersonelSatis.cshtml
@using OnlineTicaretSitesi.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Departman Personel Satış</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Personel Adı: @ViewBag.dpers</li>
</ol>

<table class="table table-condensed">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var x in Model)
    {
<tr>
    <td>@x.SatisID</td>
    <td>@x.Urun.UrunAd</td>
    <td>@x.Cariler.CariAd @x.Cariler.CariSoyad</td>
    <td>@x.Fiyat ₺</td>
    <td>@x.Adet</td>
    <td>@x.ToplamTutar</td>
    <td>@x.Tarih</td>
    <td><a href="#" class="btn btn-default" style="background-color:darksalmon">Yazdır</a></td>

</tr>
    }
</table>

OnlineTicaretSitesi/Views/Departman/Index.cshtml
@using OnlineTicaretSitesi.Models.Siniflar
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<table id="tbl1" class="table table-bordered" style="margin-top:30px">
    <thead>
    <tr>
        <th>ID</th>
        <th>Departman Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detay</th>
    </tr>
        </thead>
    @foreach (var k in Model)
    {
        <tr>
            <td>
                @k.DepartmanID
            </td>
            <td>
                @k.DepartmanAd
            </td>
            <td><a href="/Departman/DepartmanSil/@k.DepartmanID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Departman/DepartmanGetir/@k.DepartmanID" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Departman/DepartmanDetay/@k.DepartmanID" class="btn btn-default" style="color:white; background-color:cadetblue">Detay</a></td>

        </tr>
    }
</table>
<a href="/Departman/DepartmanEkle" class="btn btn-primary">Yeni Departman</a>

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#tbl1').dataTable({
        "language" : {

            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"

        }
    });
</script>